repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]
        files: ^backend/src/

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args:
          [
            "--remove-all-unused-imports",
            "--recursive",
            "--in-place",
            "--exclude=__init__.py",
          ]
        files: ^backend/src/

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        files: ^backend/src/

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=.pylintrc"]
        files: ^backend/src/
