name: Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [node, python]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for frontend)
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: "23.1.0"

      - name: Install frontend dependencies
        if: matrix.language == 'node'
        working-directory: frontend
        run: npm ci

      - name: Run ESLint
        if: matrix.language == 'node'
        working-directory: frontend
        run: npm run lint:fix

      - name: Set up Python (for backend)
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"

      - name: Install pipenv
        if: matrix.language == 'python'
        run: pip install pipenv

      - name: Install backend dependencies
        if: matrix.language == 'python'
        working-directory: backend
        run: pipenv install --dev

      - name: Run autoflake recursively in-place remove unused imports
        if: matrix.language == 'python'
        working-directory: backend
        run: pipenv run autoflake --remove-all-unused-imports --recursive --in-place --exclude=__init__.py src

      - name: Run isort
        if: matrix.language == 'python'
        working-directory: backend
        run: pipenv run isort src

      - name: Run pylint
        if: matrix.language == 'python'
        working-directory: backend
        run: pipenv run pylint src

      - name: Run Black Formatter
        if: matrix.language == 'python'
        working-directory: backend
        run: pipenv run black src
